// <auto-generated />
using System;
using Invernadero.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invernadero.Migrations
{
    [DbContext(typeof(InvernaderoContext))]
    partial class InvernaderoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invernadero.Models.CalendarioDeRiego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelAgua")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.HasKey("Id");

                    b.ToTable("CalendarioRiego", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.CalendarioDeRiegoUsuario", b =>
                {
                    b.Property<int>("IdCalendarioDeRiego")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCalendarioDeRiego", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RegistroCalendario", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.Notifica", b =>
                {
                    b.Property<int>("IdCalendarioRiego")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCalendarioRiego");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notifica", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Humedad")
                        .HasMaxLength(4)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Temperatura")
                        .HasMaxLength(4)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Registro", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.RegistroSensor", b =>
                {
                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<int>("IdSensor")
                        .HasColumnType("int");

                    b.HasKey("IdRegistro", "IdSensor");

                    b.HasIndex("IdSensor");

                    b.ToTable("RegistroSensor", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Sensor", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(9)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.UsuarioSensor", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdSensor")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdSensor");

                    b.HasIndex("IdSensor");

                    b.ToTable("RegistroConfiguración", (string)null);
                });

            modelBuilder.Entity("Invernadero.Models.CalendarioDeRiegoUsuario", b =>
                {
                    b.HasOne("Invernadero.Models.CalendarioDeRiego", "CalendarioDeRiego")
                        .WithMany("CalendarioRiegoUsuario")
                        .HasForeignKey("IdCalendarioDeRiego")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invernadero.Models.Usuario", "Usuario")
                        .WithMany("CalendarioRiegoUsuario")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarioDeRiego");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Invernadero.Models.Notifica", b =>
                {
                    b.HasOne("Invernadero.Models.CalendarioDeRiego", "CalendarioRiego")
                        .WithMany("Notificacion")
                        .HasForeignKey("IdCalendarioRiego")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invernadero.Models.Usuario", "Usuario")
                        .WithMany("Notificacion")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarioRiego");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Invernadero.Models.RegistroSensor", b =>
                {
                    b.HasOne("Invernadero.Models.Registro", "Registro")
                        .WithMany("RegistroSensor")
                        .HasForeignKey("IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invernadero.Models.Sensor", "Sensor")
                        .WithMany("RegistroSensor")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Invernadero.Models.Usuario", b =>
                {
                    b.HasOne("Invernadero.Models.Sensor", null)
                        .WithMany("Usuario")
                        .HasForeignKey("SensorId");
                });

            modelBuilder.Entity("Invernadero.Models.UsuarioSensor", b =>
                {
                    b.HasOne("Invernadero.Models.Sensor", "Sensor")
                        .WithMany("UsuarioSensor")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invernadero.Models.Usuario", "Usuario")
                        .WithMany("UsuarioSensor")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Invernadero.Models.CalendarioDeRiego", b =>
                {
                    b.Navigation("CalendarioRiegoUsuario");

                    b.Navigation("Notificacion");
                });

            modelBuilder.Entity("Invernadero.Models.Registro", b =>
                {
                    b.Navigation("RegistroSensor");
                });

            modelBuilder.Entity("Invernadero.Models.Sensor", b =>
                {
                    b.Navigation("RegistroSensor");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioSensor");
                });

            modelBuilder.Entity("Invernadero.Models.Usuario", b =>
                {
                    b.Navigation("CalendarioRiegoUsuario");

                    b.Navigation("Notificacion");

                    b.Navigation("UsuarioSensor");
                });
#pragma warning restore 612, 618
        }
    }
}
